# -*- coding: utf-8 -*-
"""
Created on Thu Aug 19 15:01:17 2021

@author: Grant Isaacs
"""

#IMPORT LIBRARIES------------------------------------------------------------->
import pandas as pd




#LOAD DATA-------------------------------------------------------------------->
"""The data can be located at
    https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data
"""
dataset = pd.read_csv("ab_nyc_2019.csv")




#INDEXING--------------------------------------------------------------------->
"""The default index generated by Pandas starts at zero and counts up.
Some data will contain a database index or some other unique identifier.
.set_index can be used to assign an alternative index to the observations."""
dataset_01 = dataset.set_index("id")
print(dataset_01.head())

"""A row can be called by the index number."""
print(dataset_01.host_name[5441])
print(dataset_01['host_name'][5441])

"""At times pandas may assign an alternative index to an observation such as when grouping.
.reset_index without arguments will assign a default index and move the alternative index into a column."""
dataset_02 = dataset.groupby("room_type").mean()
print(dataset_02.index)
dataset_02 = dataset_02.reset_index()
print(dataset_02.index)

"""If the drop paramter is set to true, instead of assigning the previous index to a column,
pandas will drop the information from the dataframe."""
dataset_03 = dataset.groupby("room_type").mean()
print(dataset_03.index)
dataset_03 = dataset_03.reset_index(drop = True)
print(dataset_03.index)




#SORTING---------------------------------------------------------------------->
""".sort_index sorts the index in ascending order."""
dataset_04 = dataset.set_index("id")
dataset_04 = dataset_04.sort_index(ascending=False)

""".sort_values sorts by the vales in one or more columns."""
dataset_04 = dataset_04.sort_values("host_name")
dataset_04 = dataset_04.sort_values(["neighbourhood_group", "host_name"], ascending = [False, True])




#RANKING---------------------------------------------------------------------->
"""Ranking soprts with collision detection.
Some available arguments for the method parameter are 'average', 'max', 'min'.
A good source for additional information is:
    https://www.w3resource.com/pandas/dataframe/dataframe-rank.php
"""
dataset_05 = dataset[["id", "host_name", "price"]]
dataset_05 = dataset_05.sort_values("price", ascending = False)
dataset_05["price_rank"] = dataset_05["price"].rank(method="average", ascending = False)
print(dataset_05[["id", "host_name", "price", "price_rank"]])
